<?php declare(strict_types=1); namespace AteEducacion\CanariasRouteMatrix;
use AteEducacion\CanariasRouteMatrix\Exception\{CrossIslandRouteException,InvalidFormatException,UnknownCenterException,UnreachableRouteException};
final class Reader {
 private const INDEX_SIZE=12; private const DIRECTORY_SIZE=24; private const UNREACHABLE=0xFFFFFFFF; private $handle; private int $size; private int $count; private int $indexOffset; private array $islands=[];
 public function __construct(string $binaryPath, ?string $centersPath=null, bool $preloadIndex=false, bool $preloadFile=false){$this->size=filesize($binaryPath)?:0;$this->handle=fopen($binaryPath,"rb");if($this->handle===false)throw new InvalidFormatException("Cannot open binary");$h=$this->read(0,64);if(substr($h,0,8)!=="CEDIST01")throw new InvalidFormatException("Unknown magic");if($this->u16($h,8)>1||$this->u32($h,12)!==64||$this->u32($h,16)!==0||$this->u16($h,22)!==0||substr($h,52,12)!==str_repeat("\0",12))throw new InvalidFormatException("Invalid header");$islandCount=$this->u16($h,20);$this->count=$this->u32($h,24);$this->indexOffset=$this->u64($h,28);$directory=$this->u64($h,36);if($this->u64($h,44)!==$this->size||$this->indexOffset!==64||$directory!==64+$this->count*self::INDEX_SIZE)throw new InvalidFormatException("Invalid offsets");for($i=0;$i<$islandCount;$i++){$e=$this->read($directory+$i*self::DIRECTORY_SIZE,24);$id=ord($e[0]);$n=$this->u32($e,4);$distance=$this->u64($e,8);$duration=$this->u64($e,16);if(substr($e,1,3)!=="\0\0\0"||$duration!==$distance+$n*$n*4||$duration+$n*$n*4>$this->size)throw new InvalidFormatException("Invalid island directory");$this->islands[$id]=[$n,$distance,$duration];}}
 private function read(int $offset,int $length):string{if($offset<0||$length<0||$offset>$this->size-$length||fseek($this->handle,$offset)!==0)throw new InvalidFormatException("Out-of-range read");$value=fread($this->handle,$length);if($value===false||strlen($value)!==$length)throw new InvalidFormatException("Truncated file");return $value;}
 private function u16(string $s,int $o):int{return unpack("v",substr($s,$o,2))[1];} private function u32(string $s,int $o):int{return unpack("V",substr($s,$o,4))[1];} private function u64(string $s,int $o):int{$v=unpack("Vlow/Vhigh",substr($s,$o,8));if($v["high"]>0x1FFFFF)throw new InvalidFormatException("Offset overflow");return $v["low"]+$v["high"]*4294967296;}
 private function find(string $code):array{if(!preg_match('/^[0-9]{8}$/D',$code))throw new UnknownCenterException("Invalid center code");$target=(int)$code;$low=0;$high=$this->count-1;while($low<=$high){$mid=intdiv($low+$high,2);$e=$this->read($this->indexOffset+$mid*self::INDEX_SIZE,12);$value=$this->u32($e,0);if($value===$target){$id=ord($e[4]);$local=$this->u16($e,6);if(!isset($this->islands[$id])||$local>=$this->islands[$id][0])throw new InvalidFormatException("Index/island mismatch");return [$id,$local];}if($value<$target)$low=$mid+1;else$high=$mid-1;}throw new UnknownCenterException("Unknown center: $code");}
 public function getRoute(string $origin,string $destination):RouteResult{[$a,$ai]=$this->find($origin);[$b,$bi]=$this->find($destination);if($a!==$b)throw new CrossIslandRouteException("Routes between islands are not computed");[$n,$distanceOffset,$durationOffset]=$this->islands[$a];$p=$ai*$n+$bi;$distance=$this->u32($this->read($distanceOffset+$p*4,4),0);$duration=$this->u32($this->read($durationOffset+$p*4,4),0);if($distance===self::UNREACHABLE||$duration===self::UNREACHABLE)throw new UnreachableRouteException("Route is unavailable");return new RouteResult($distance,$duration);}
}
